# KED'S ALACRITTY CONFIG
# MAIN CONFIG FILE [ALACRITTY.YML]
# (C) 2023 Kedislav - File under GNU GPL v3.0
#///////////////////////////////////////////////////////////////////
# Colors and Fonts are saved in their respective separate files.
#///////////////////////////////////////////////////////////////////

#//import files and configs
import:
  - ~/.config/alacritty/colors.yml
  - ~/.config/alacritty/fonts.yml

#//env variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

#//terminal window settings
window:
  dimensions:
    columns: 82
    lines: 25
  padding:
    x: 15
    y: 15
  decorations: full
  startup_mode: Windowed
  dynamic_title: true
#//scrolling
  history: 10000
  multiplier: 3
#//bg opacity
  opacity: 1.0
#//terminal cursor
cursor:
  style:
    shape: Block
    blinking: On
  unfocused_hollow: false

#//live config reload
live_config_reload: true
